// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: analyzer/v1/analyzer.proto

package analyzerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Action int32

const (
	Action_ALLOW Action = 0 // forward as-is
	Action_BLOCK Action = 1 // reject; return 403 to the client
	Action_MASK  Action = 2 // forward with masked_prompt replacing original
)

// Enum value maps for Action.
var (
	Action_name = map[int32]string{
		0: "ALLOW",
		1: "BLOCK",
		2: "MASK",
	}
	Action_value = map[string]int32{
		"ALLOW": 0,
		"BLOCK": 1,
		"MASK":  2,
	}
)

func (x Action) Enum() *Action {
	p := new(Action)
	*p = x
	return p
}

func (x Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action) Descriptor() protoreflect.EnumDescriptor {
	return file_analyzer_v1_analyzer_proto_enumTypes[0].Descriptor()
}

func (Action) Type() protoreflect.EnumType {
	return &file_analyzer_v1_analyzer_proto_enumTypes[0]
}

func (x Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action.Descriptor instead.
func (Action) EnumDescriptor() ([]byte, []int) {
	return file_analyzer_v1_analyzer_proto_rawDescGZIP(), []int{0}
}

type PromptRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	TenantId  string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// The full prompt text extracted from the LLM request body.
	Prompt        string `protobuf:"bytes,3,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Model         string `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromptRequest) Reset() {
	*x = PromptRequest{}
	mi := &file_analyzer_v1_analyzer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptRequest) ProtoMessage() {}

func (x *PromptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analyzer_v1_analyzer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptRequest.ProtoReflect.Descriptor instead.
func (*PromptRequest) Descriptor() ([]byte, []int) {
	return file_analyzer_v1_analyzer_proto_rawDescGZIP(), []int{0}
}

func (x *PromptRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *PromptRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *PromptRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *PromptRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type ThreatDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`               // e.g. "PromptInjection", "Jailbreak"
	Confidence    float32                `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"` // 0.0–1.0
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThreatDetail) Reset() {
	*x = ThreatDetail{}
	mi := &file_analyzer_v1_analyzer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreatDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreatDetail) ProtoMessage() {}

func (x *ThreatDetail) ProtoReflect() protoreflect.Message {
	mi := &file_analyzer_v1_analyzer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreatDetail.ProtoReflect.Descriptor instead.
func (*ThreatDetail) Descriptor() ([]byte, []int) {
	return file_analyzer_v1_analyzer_proto_rawDescGZIP(), []int{1}
}

func (x *ThreatDetail) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ThreatDetail) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *ThreatDetail) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type AnalysisResult struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Action    Action                 `protobuf:"varint,2,opt,name=action,proto3,enum=analyzer.v1.Action" json:"action,omitempty"`
	// risk_score is 0.0–100.0 and feeds directly into Cedar's ABAC context,
	// replacing the hardcoded value from Phase 1.
	RiskScore   float32 `protobuf:"fixed32,3,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	PiiDetected bool    `protobuf:"varint,4,opt,name=pii_detected,json=piiDetected,proto3" json:"pii_detected,omitempty"`
	// masked_prompt is populated when action == MASK; the gateway must forward
	// this text in place of the original prompt.
	MaskedPrompt  string          `protobuf:"bytes,5,opt,name=masked_prompt,json=maskedPrompt,proto3" json:"masked_prompt,omitempty"`
	Threats       []*ThreatDetail `protobuf:"bytes,6,rep,name=threats,proto3" json:"threats,omitempty"`
	Reason        string          `protobuf:"bytes,7,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalysisResult) Reset() {
	*x = AnalysisResult{}
	mi := &file_analyzer_v1_analyzer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisResult) ProtoMessage() {}

func (x *AnalysisResult) ProtoReflect() protoreflect.Message {
	mi := &file_analyzer_v1_analyzer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisResult.ProtoReflect.Descriptor instead.
func (*AnalysisResult) Descriptor() ([]byte, []int) {
	return file_analyzer_v1_analyzer_proto_rawDescGZIP(), []int{2}
}

func (x *AnalysisResult) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AnalysisResult) GetAction() Action {
	if x != nil {
		return x.Action
	}
	return Action_ALLOW
}

func (x *AnalysisResult) GetRiskScore() float32 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *AnalysisResult) GetPiiDetected() bool {
	if x != nil {
		return x.PiiDetected
	}
	return false
}

func (x *AnalysisResult) GetMaskedPrompt() string {
	if x != nil {
		return x.MaskedPrompt
	}
	return ""
}

func (x *AnalysisResult) GetThreats() []*ThreatDetail {
	if x != nil {
		return x.Threats
	}
	return nil
}

func (x *AnalysisResult) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_analyzer_v1_analyzer_proto protoreflect.FileDescriptor

const file_analyzer_v1_analyzer_proto_rawDesc = "" +
	"\n" +
	"\x1aanalyzer/v1/analyzer.proto\x12\vanalyzer.v1\"y\n" +
	"\rPromptRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x16\n" +
	"\x06prompt\x18\x03 \x01(\tR\x06prompt\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\"d\n" +
	"\fThreatDetail\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02R\n" +
	"confidence\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\x90\x02\n" +
	"\x0eAnalysisResult\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12+\n" +
	"\x06action\x18\x02 \x01(\x0e2\x13.analyzer.v1.ActionR\x06action\x12\x1d\n" +
	"\n" +
	"risk_score\x18\x03 \x01(\x02R\triskScore\x12!\n" +
	"\fpii_detected\x18\x04 \x01(\bR\vpiiDetected\x12#\n" +
	"\rmasked_prompt\x18\x05 \x01(\tR\fmaskedPrompt\x123\n" +
	"\athreats\x18\x06 \x03(\v2\x19.analyzer.v1.ThreatDetailR\athreats\x12\x16\n" +
	"\x06reason\x18\a \x01(\tR\x06reason*(\n" +
	"\x06Action\x12\t\n" +
	"\x05ALLOW\x10\x00\x12\t\n" +
	"\x05BLOCK\x10\x01\x12\b\n" +
	"\x04MASK\x10\x022[\n" +
	"\x0fAnalyzerService\x12H\n" +
	"\rAnalyzePrompt\x12\x1a.analyzer.v1.PromptRequest\x1a\x1b.analyzer.v1.AnalysisResultBHZFgithub.com/sharvik/llm-firewall/gateway/internal/analyzerpb;analyzerpbb\x06proto3"

var (
	file_analyzer_v1_analyzer_proto_rawDescOnce sync.Once
	file_analyzer_v1_analyzer_proto_rawDescData []byte
)

func file_analyzer_v1_analyzer_proto_rawDescGZIP() []byte {
	file_analyzer_v1_analyzer_proto_rawDescOnce.Do(func() {
		file_analyzer_v1_analyzer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analyzer_v1_analyzer_proto_rawDesc), len(file_analyzer_v1_analyzer_proto_rawDesc)))
	})
	return file_analyzer_v1_analyzer_proto_rawDescData
}

var file_analyzer_v1_analyzer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_analyzer_v1_analyzer_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_analyzer_v1_analyzer_proto_goTypes = []any{
	(Action)(0),            // 0: analyzer.v1.Action
	(*PromptRequest)(nil),  // 1: analyzer.v1.PromptRequest
	(*ThreatDetail)(nil),   // 2: analyzer.v1.ThreatDetail
	(*AnalysisResult)(nil), // 3: analyzer.v1.AnalysisResult
}
var file_analyzer_v1_analyzer_proto_depIdxs = []int32{
	0, // 0: analyzer.v1.AnalysisResult.action:type_name -> analyzer.v1.Action
	2, // 1: analyzer.v1.AnalysisResult.threats:type_name -> analyzer.v1.ThreatDetail
	1, // 2: analyzer.v1.AnalyzerService.AnalyzePrompt:input_type -> analyzer.v1.PromptRequest
	3, // 3: analyzer.v1.AnalyzerService.AnalyzePrompt:output_type -> analyzer.v1.AnalysisResult
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_analyzer_v1_analyzer_proto_init() }
func file_analyzer_v1_analyzer_proto_init() {
	if File_analyzer_v1_analyzer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analyzer_v1_analyzer_proto_rawDesc), len(file_analyzer_v1_analyzer_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_analyzer_v1_analyzer_proto_goTypes,
		DependencyIndexes: file_analyzer_v1_analyzer_proto_depIdxs,
		EnumInfos:         file_analyzer_v1_analyzer_proto_enumTypes,
		MessageInfos:      file_analyzer_v1_analyzer_proto_msgTypes,
	}.Build()
	File_analyzer_v1_analyzer_proto = out.File
	file_analyzer_v1_analyzer_proto_goTypes = nil
	file_analyzer_v1_analyzer_proto_depIdxs = nil
}
