{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "titan.fullname" . }}-secrets
  labels: {{- include "titan.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-token: {{ .Values.secrets.adminToken | quote }}
  provider-api-key: {{ .Values.secrets.providerAPIKey | quote }}
  fallback-api-key: {{ .Values.secrets.fallbackAPIKey | quote }}
{{- end }}
