# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analyzer/v1/analyzer.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'analyzer/v1/analyzer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x61nalyzer/v1/analyzer.proto\x12\x0b\x61nalyzer.v1\"U\n\rPromptRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x11\n\ttenant_id\x18\x02 \x01(\t\x12\x0e\n\x06prompt\x18\x03 \x01(\t\x12\r\n\x05model\x18\x04 \x01(\t\"E\n\x0cThreatDetail\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"\xc6\x01\n\x0e\x41nalysisResult\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12#\n\x06\x61\x63tion\x18\x02 \x01(\x0e\x32\x13.analyzer.v1.Action\x12\x12\n\nrisk_score\x18\x03 \x01(\x02\x12\x14\n\x0cpii_detected\x18\x04 \x01(\x08\x12\x15\n\rmasked_prompt\x18\x05 \x01(\t\x12*\n\x07threats\x18\x06 \x03(\x0b\x32\x19.analyzer.v1.ThreatDetail\x12\x0e\n\x06reason\x18\x07 \x01(\t*(\n\x06\x41\x63tion\x12\t\n\x05\x41LLOW\x10\x00\x12\t\n\x05\x42LOCK\x10\x01\x12\x08\n\x04MASK\x10\x02\x32[\n\x0f\x41nalyzerService\x12H\n\rAnalyzePrompt\x12\x1a.analyzer.v1.PromptRequest\x1a\x1b.analyzer.v1.AnalysisResultBHZFgithub.com/sharvik/llm-firewall/gateway/internal/analyzerpb;analyzerpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analyzer.v1.analyzer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZFgithub.com/sharvik/llm-firewall/gateway/internal/analyzerpb;analyzerpb'
  _globals['_ACTION']._serialized_start=402
  _globals['_ACTION']._serialized_end=442
  _globals['_PROMPTREQUEST']._serialized_start=43
  _globals['_PROMPTREQUEST']._serialized_end=128
  _globals['_THREATDETAIL']._serialized_start=130
  _globals['_THREATDETAIL']._serialized_end=199
  _globals['_ANALYSISRESULT']._serialized_start=202
  _globals['_ANALYSISRESULT']._serialized_end=400
  _globals['_ANALYZERSERVICE']._serialized_start=444
  _globals['_ANALYZERSERVICE']._serialized_end=535
# @@protoc_insertion_point(module_scope)
